---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: "$GRAFANA_NAME"
  labels:
    app: grafana
spec:
  # Service account for the Grafana Operator to manage datasources and dashboards
  serviceAccount:
    metadata:
      annotations: {}
      labels: {}

  deployment:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: grafana

  persistentVolumeClaim:
    spec:
      resources:
        requests:
          storage: 1G
      accessModes:
        - ReadWriteOnce

  client:
    timeout: 30
    preferIngress: False
  config:
    log:
      mode: "console"
      level: "debug"
    security:
      admin_user: "$GRAFANA_ADMIN_USER"
      admin_password: "$GRAFANA_ADMIN_PASSWORD"
    auth:
      disable_login_form: "$GRAFANA_DISABLE_LOGIN_FORM"
      disable_signout_menu: "$GRAFANA_DISABLE_SIGNOUT_MENU"
    # required for Dashboard Installation - https://github.com/integr8ly/grafana-operator/issues/92
    auth.basic:
      enabled: "True"
    dataproxy:
      timeout: "600"
    auth.anonymous:
      enabled: "$GRAFANA_ANONYMOUS_EDITOR"
      org_role: Editor
# look to https://grafana.com/docs/grafana/latest/auth/generic-oauth/
#    server:
#      root_url: $GRAFANA_ROOT_URL
#    auth.generic_oauth:
#      enabled: True
#      name: OAuth
#      allow_sign_up: True
#      allowed_domains: $OAUTH_ALLOWED_DOMAINS
#      team_ids: $OAUTH_ALLOWED_TEAM_IDS
#      allowed_organizations: $OAUTH_ALLOWED_ORGANIZATIONS
#      client_id: $OAUTH_CLIENT_ID
#      client_secret: $OAUTH_CLIENT_SECRET
#      scopes: openid profile email
#      auth_url: https://$OAUTH_DOMAIN/authorize
#      token_url: https://$OAUTH_DOMAIN/oauth/token
#      api_url: https://$OAUTH_DOMAIN/userinfo