# Possible Template Parameters:
#
# clickhouse-dev-mfs
# sunsingerus/clickhouse-operator:dev
#
# Setup CustomResourceDefinition
# CustomResourceDefinition is namespace-less and must have unique name
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clickhouseinstallations.clickhouse.altinity.com
spec:
  group: clickhouse.altinity.com
  version: v1
  scope: Namespaced
  names:
    kind: ClickHouseInstallation
    singular: clickhouseinstallation
    plural: clickhouseinstallations
    shortNames:
      - chi
  additionalPrinterColumns:
    - name: version
      type: string
      description: Operator version
      JSONPath: .status.version
    - name: clusters
      type: integer
      description: Clusters count
      JSONPath: .status.clusters
    - name: replicas
      type: integer
      description: Replicas count
      JSONPath: .status.replicas
    - name: endpoint
      type: string
      description: Client access endpoint
      JSONPath: .status.endpoint
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            defaults:
              type: object
              properties:
                # Need to be string-bool
                replicasUseFQDN:
                  type: string
                distributedDDL:
                  type: object
                  properties:
                    profile:
                      type: string
                templates:
                  type: object
                  properties:
                    podTemplate:
                      type: string
                    volumeClaimTemplate:
                      type: string
            configuration:
              type: object
              properties:
                zookeeper:
                  type: object
                  properties:
                    nodes:
                      type: array
                      items:
                        type: object
                        required:
                          - host
                        properties:
                          host:
                            type: string
                          port:
                            type: integer
                            minimum: 1
                users:
                  type: object
                profiles:
                  type: object
                quotas:
                  type: object
                settings:
                  type: object
                clusters:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        pattern: "^[a-zA-Z]([a-zA-Z0-9_-]){0,14}$"
                      shardsCount:
                        type: integer
                        minimum: 1
                      replicasCount:
                        type: integer
                        minimum: 1
                      templates:
                        type: object
                        properties:
                          podTemplate:
                            type: string
                          volumeClaimTemplate:
                            type: string
                      layout:
                        type: object
                        properties:
                          # DEPRECATED - to be removed soon
                          type:
                            type: string
                          shardsCount:
                            type: integer
                          replicasCount:
                            type: integer
                          shards:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                  pattern: "^([a-zA-Z0-9_-]){0,8}$"
                                # DEPRECATED - to be removed soon
                                definitionType:
                                  type: string
                                replicasCount:
                                  type: integer
                                  minimum: 1
                                weight:
                                  type: integer
                                # Need to be string-bool
                                internalReplication:
                                  type: string
                                templates:
                                  type: object
                                  properties:
                                    podTemplate:
                                      type: string
                                    volumeClaimTemplate:
                                      type: string
                                replicas:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      name:
                                        type: string
                                        pattern: "^([a-zA-Z0-9_-]){0,8}$"
                                      port:
                                        type: integer
                                        minimum: 1
                                      templates:
                                        type: object
                                        properties:
                                          podTemplate:
                                            type: string
                                          volumeClaimTemplate:
                                            type: string
            templates:
              type: object
              properties:
                volumeClaimTemplates:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - spec
                    properties:
                      name:
                        type: string
                      spec:
                        # TODO specify PersistentVolumeClaimSpec
                        type: object
                podTemplates:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - spec
                    properies:
                      name:
                        type: string
                      spec:
                        # TODO specify PodSpec
                        type: object
---
# Possible Template Parameters:
#
# clickhouse-dev-mfs
# sunsingerus/clickhouse-operator:dev
#
# Setup ServiceAccount
# ServiceAccount would be created in kubectl-specified namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-operator
  namespace: clickhouse-dev-mfs
---
# Setup ClusterRoleBinding between ClusterRole and ServiceAccount.
# ClusterRoleBinding is namespace-less and must have unique name
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: clickhouse-operator
    namespace: clickhouse-dev-mfs
---
# Setup ClusterIP Service to provide monitoring metrics for Prometheus
# Service would be created in kubectl-specified namespace
# In order to get access outside of k8s it should be exposed as:
# kubectl --namespace prometheus port-forward service/prometheus 9090
# and point browser to localhost:9090
kind: Service
apiVersion: v1
metadata:
  name: clickhouse-operator-metrics
  namespace: clickhouse-dev-mfs
  labels:
    app: clickhouse-operator
spec:
  ports:
    - port: 8888
      name: clickhouse-operator-metrics
  selector:
    app: clickhouse-operator
---
# Possible Template Parameters:
#
# clickhouse-dev-mfs
# sunsingerus/clickhouse-operator:dev
# etc-clickhouse-operator-files
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-clickhouse-operator-files
  namespace: clickhouse-dev-mfs
data:
  config.yaml: |
    # Namespaces where clickhouse-operator listens for events.
    # Concurrently running operators should listen on different namespaces
    # namespaces:
    #  - dev
    #  - info
    #  - onemore
    
    ################################################
    ##
    ## Additional Configuration Files Section
    ##
    ################################################
    
    # Path to folder where ClickHouse configuration files common for all instances within CHI are located.
    chCommonConfigsPath: config.d
    
    # Path to folder where ClickHouse configuration files unique for each instances within CHI are located.
    chDeploymentConfigsPath: conf.d
    
    # Path to folder where ClickHouse configuration files with users settings are located.
    # Files are common for all instances within CHI
    chUsersConfigsPath: users.d
    
    # Path to folder where ClickHouseInstallation .yaml manifests are located.
    # Manifests are applied in sorted alpha-numeric order
    chiTemplatesPath: templates.d
    
    ################################################
    ##
    ## Cluster Create/Update/Delete Objects Section
    ##
    ################################################
    
    # How many seconds to wait for created/updated StatefulSet to be Ready
    statefulSetUpdateTimeout: 600
    
    # How many seconds to wait between checks for created/updated StatefulSet status
    statefulSetUpdatePollPeriod: 10
    
    # What to do in case created StatefulSet is not in Ready after `statefulSetUpdateTimeout` seconds
    # Possible options:
    # 1. abort - do nothing, just break the process and wait for admin
    # 2. delete - delete newly created problematic StatefulSet
    onStatefulSetCreateFailureAction: delete
    
    # What to do in case updated StatefulSet is not in Ready after `statefulSetUpdateTimeout` seconds
    # Possible options:
    # 1. abort - do nothing, just break the process and wait for admin
    # 2. rollback - delete Pod and rollback StatefulSet to previous Generation.
    # Pod would be recreated by StatefulSet based on rollback-ed configuration
    onStatefulSetUpdateFailureAction: rollback
    
    ################################################
    ##
    ## ClickHouse Settings Section
    ##
    ################################################
    
    # Default values for ClickHouse user configuration
    # 1. user/profile - string
    # 2. user/quota - string
    # 3. user/networks/ip - multiple strings
    # 4. user/password - string
    chConfigUserDefaultProfile: default
    chConfigUserDefaultQuota: default
    chConfigUserDefaultNetworksIP:
      - "::/0"
    chConfigUserDefaultPassword: "default"
    
    ################################################
    ##
    ## Operator's access to ClickHouse instances
    ##
    ################################################
    
    # ClickHouse credentials (username, password and port) to be used by operator to connect to ClickHouse instances for:
    # 1. Metrics requests
    # 2. Schema maintenance
    # 3. DROP DNS CACHE
    # User with such credentials credentials can be specified in additional ClickHouse .xml config files,
    # located in `chUsersConfigsPath` folder
    chUsername: clickhouse_operator
    chPassword: clickhouse_operator_password
    chPort: 8123

---
# Possible Template Parameters:
#
# clickhouse-dev-mfs
# sunsingerus/clickhouse-operator:dev
# etc-clickhouse-operator-confd-files
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-clickhouse-operator-confd-files
  namespace: clickhouse-dev-mfs
data:
---
# Possible Template Parameters:
#
# clickhouse-dev-mfs
# sunsingerus/clickhouse-operator:dev
# etc-clickhouse-operator-configd-files
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-clickhouse-operator-configd-files
  namespace: clickhouse-dev-mfs
data:
  01-clickhouse-operator-listen.xml: |
    <yandex>
        <!-- Listen wildcard address to allow accepting connections from other containers and host network. -->
        <listen_host>::</listen_host>
        <listen_host>0.0.0.0</listen_host>
        <listen_try>1</listen_try>
    </yandex>

  02-clickhouse-operator-logger.xml: |
    <yandex>
        <logger>
            <console>1</console>
        </logger>
    </yandex>

---
# Possible Template Parameters:
#
# clickhouse-dev-mfs
# sunsingerus/clickhouse-operator:dev
# etc-clickhouse-operator-templatesd-files
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-clickhouse-operator-templatesd-files
  namespace: clickhouse-dev-mfs
data:
---
# Possible Template Parameters:
#
# clickhouse-dev-mfs
# sunsingerus/clickhouse-operator:dev
# etc-clickhouse-operator-usersd-files
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-clickhouse-operator-usersd-files
  namespace: clickhouse-dev-mfs
data:
  01-clickhouse-operator-user.xml: |
    <yandex>
        <users>
            <clickhouse_operator>
                <networks>
                    <ip>127.0.0.1</ip>
                    <ip>0.0.0.0/0</ip>
                    <ip>::/0</ip>
                </networks>
                <password>clickhouse_operator_password</password>
                <profile>default</profile>
                <quota>default</quota>
            </clickhouse_operator>
        </users>
    </yandex>

---
# Possible Template Parameters:
#
# clickhouse-dev-mfs
# sunsingerus/clickhouse-operator:dev
#
# Setup Deployment for clickhouse-operator
# Deployment would be created in kubectl-specified namespace
kind: Deployment
apiVersion: apps/v1
metadata:
  name: clickhouse-operator
  namespace: clickhouse-dev-mfs
  labels:
    app: clickhouse-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-operator
  template:
    metadata:
      labels:
        app: clickhouse-operator
    spec:
      serviceAccountName: clickhouse-operator
      volumes:
        - name: etc-clickhouse-operator-folder
          configMap:
            name: etc-clickhouse-operator-files
        - name: etc-clickhouse-operator-confd-folder
          configMap:
            name: etc-clickhouse-operator-confd-files
        - name: etc-clickhouse-operator-configd-folder
          configMap:
            name: etc-clickhouse-operator-configd-files
        - name: etc-clickhouse-operator-templatesd-folder
          configMap:
            name: etc-clickhouse-operator-templatesd-files
        - name: etc-clickhouse-operator-usersd-folder
          configMap:
            name: etc-clickhouse-operator-usersd-files
      containers:
        - name: clickhouse-operator
          image: sunsingerus/clickhouse-operator:dev
          imagePullPolicy: Always
          volumeMounts:
            - name: etc-clickhouse-operator-folder
              mountPath: /etc/clickhouse-operator
            - name: etc-clickhouse-operator-confd-folder
              mountPath: /etc/clickhouse-operator/conf.d
            - name: etc-clickhouse-operator-configd-folder
              mountPath: /etc/clickhouse-operator/config.d
            - name: etc-clickhouse-operator-templatesd-folder
              mountPath: /etc/clickhouse-operator/templates.d
            - name: etc-clickhouse-operator-usersd-folder
              mountPath: /etc/clickhouse-operator/users.d
          env:
            # Pod-specific
            # spec.nodeName: ip-172-20-52-62.ec2.internal
            - name: OPERATOR_POD_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # metadata.name: clickhouse-operator-6f87589dbb-ftcsf
            - name: OPERATOR_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # metadata.namespace: kube-system
            - name: OPERATOR_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # status.podIP: 100.96.3.2
            - name: OPERATOR_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # spec.serviceAccount: clickhouse-operator
            # spec.serviceAccountName: clickhouse-operator
            - name: OPERATOR_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName

            # Container-specific
            - name: OPERATOR_CONTAINER_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: clickhouse-operator
                  resource: requests.cpu
            - name: OPERATOR_CONTAINER_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: clickhouse-operator
                  resource: limits.cpu
            - name: OPERATOR_CONTAINER_MEM_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: clickhouse-operator
                  resource: requests.memory
            - name: OPERATOR_CONTAINER_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: clickhouse-operator
                  resource: limits.memory
