apiVersion: v2
name: altinity-clickhouse-operator
description: |-
  Helm chart to deploy [altinity-clickhouse-operator](https://github.com/Altinity/clickhouse-operator).

  The ClickHouse Operator creates, configures and manages ClickHouse clusters running on Kubernetes.
type: application
version: 0.21.1
appVersion: 0.21.1
home: https://github.com/Altinity/clickhouse-operator
icon: https://logosandtypes.com/wp-content/uploads/2020/12/altinity.svg
maintainers:
  - name: altinity
    email: support@altinity.com
