## JOB for create Bucket
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: minio-client
          image: "minio/mc:${MINIO_CLIENT_VERSION}"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -xc
            - mc alias set miniok8s https://minio-hl.minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} --insecure && mc mb miniok8s/${MINIO_BACKUP_BUCKET} --ignore-existing --insecure

  backoffLimit: 10
