# Possible Template Parameters:
#
# ${CHOPERATOR_NAMESPACE}
# ${CHOPERATOR_IMAGE}
#
# Setup CustomResourceDefinition
# CustomResourceDefinition is namespace-less and must have unique name
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clickhouseinstallations.clickhouse.altinity.com
spec:
  group: clickhouse.altinity.com
  version: v1
  scope: Namespaced
  names:
    kind: ClickHouseInstallation
    singular: clickhouseinstallation
    plural: clickhouseinstallations
    shortNames:
      - chi
  additionalPrinterColumns:
    - name: version
      type: string
      description: Operator version
      JSONPath: .status.version
    - name: clusters
      type: integer
      description: Clusters count
      JSONPath: .status.clusters
    - name: replicas
      type: integer
      description: Replicas count
      JSONPath: .status.replicas
    - name: endpoint
      type: string
      description: Client access endpoint
      JSONPath: .status.endpoint
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            defaults:
              type: object
              properties:
                # Need to be string-bool
                replicasUseFQDN:
                  type: string
                distributedDDL:
                  type: object
                  properties:
                    profile:
                      type: string
                templates:
                  type: object
                  properties:
                    podTemplate:
                      type: string
                    volumeClaimTemplate:
                      type: string
                    serviceTemplate:
                      type: string
            configuration:
              type: object
              properties:
                zookeeper:
                  type: object
                  properties:
                    nodes:
                      type: array
                      items:
                        type: object
                        required:
                          - host
                        properties:
                          host:
                            type: string
                          port:
                            type: integer
                            minimum: 1
                users:
                  type: object
                profiles:
                  type: object
                quotas:
                  type: object
                settings:
                  type: object
                clusters:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        pattern: "^[a-zA-Z]([a-zA-Z0-9_-]){0,14}$"
                      shardsCount:
                        type: integer
                        minimum: 1
                      replicasCount:
                        type: integer
                        minimum: 1
                      templates:
                        type: object
                        properties:
                          podTemplate:
                            type: string
                          volumeClaimTemplate:
                            type: string
                          serviceTemplate:
                            type: string
                      layout:
                        type: object
                        properties:
                          # DEPRECATED - to be removed soon
                          type:
                            type: string
                          shardsCount:
                            type: integer
                          replicasCount:
                            type: integer
                          shards:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                  pattern: "^([a-zA-Z0-9_-]){0,8}$"
                                # DEPRECATED - to be removed soon
                                definitionType:
                                  type: string
                                replicasCount:
                                  type: integer
                                  minimum: 1
                                weight:
                                  type: integer
                                # Need to be string-bool
                                internalReplication:
                                  type: string
                                templates:
                                  type: object
                                  properties:
                                    podTemplate:
                                      type: string
                                    volumeClaimTemplate:
                                      type: string
                                    serviceTemplate:
                                      type: string
                                replicas:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      name:
                                        type: string
                                        pattern: "^([a-zA-Z0-9_-]){0,8}$"
                                      port:
                                        type: integer
                                        minimum: 1
                                      templates:
                                        type: object
                                        properties:
                                          podTemplate:
                                            type: string
                                          volumeClaimTemplate:
                                            type: string
                                          serviceTemplate:
                                            type: string
            templates:
              type: object
              properties:
                podTemplates:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - spec
                    properies:
                      name:
                        type: string
                      zone:
                        type: object
                        required:
                          - values
                        properties:
                          key:
                            type: string
                          values:
                            type: array
                            items:
                              type: string
                      distribution:
                        type: string
                        enum:
                          - OnePerHost
                      spec:
                        # TODO specify PodSpec
                        type: object
                volumeClaimTemplates:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - spec
                    properties:
                      name:
                        type: string
                      reclaimPolicy:
                        type: string
                        enum:
                          - Retain
                          - Delete
                      spec:
                        # TODO specify PersistentVolumeClaimSpec
                        type: object
                serviceTemplates:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - spec
                    properties:
                      name:
                        type: string
                      spec:
                        # TODO specify ServiceSpec
                        type: object
